import { Products } from "./interfaces";
import { Slides } from "./interfaces";
import { Smartphone } from "lucide-react";

export const products: Products[] = [
  {
    id: 1,
    name: "HAVIT HV-G92 Gamepad",
    price: 120,
    originalPrice: 160,
    discount: 40,
    rating: 5,
    reviews: 88,
    image: "/iphone16.png",
  },
  {
    id: 2,
    name: "AK-900 Wired Keyboard",
    price: 960,
    originalPrice: 1160,
    discount: 35,
    rating: 4.5,
    reviews: 75,
    image: "/iphone16.png",
  },
  {
    id: 3,
    name: "HAVIT HV-KB558CM Keyboard",
    price: 120,
    originalPrice: 160,
    discount: 40,
    rating: 4.5,
    reviews: 88,
    image: "/iphone16.png",
  },
  {
    id: 4,
    name: "HAVIT HV-G92 Gamepad",
    price: 120,
    originalPrice: 160,
    discount: 40,
    rating: 5,
    reviews: 88,
    image: "/iphone16.png",
  },
  {
    id: 5,
    name: "AK-900 Wired Keyboard",
    price: 960,
    originalPrice: 1160,
    discount: 35,
    rating: 4.5,
    reviews: 75,
    image: "/iphone16.png",
  },
  {
    id: 6,
    name: "HAVIT HV-KB558CM Keyboard",
    price: 120,
    originalPrice: 160,
    discount: 40,
    rating: 4.5,
    reviews: 88,
    image: "/iphone16.png",
  },
  {
    id: 7,
    name: "HAVIT HV-G92 Gamepad",
    price: 120,
    originalPrice: 160,
    discount: 40,
    rating: 5,
    reviews: 88,
    image: "/iphone16.png",
  },
  {
    id: 8,
    name: "AK-900 Wired Keyboard",
    price: 960,
    originalPrice: 1160,
    discount: 35,
    rating: 4.5,
    reviews: 75,
    image: "/iphone16.png",
  },
  {
    id: 9,
    name: "HAVIT HV-KB558CM Keyboard",
    price: 120,
    originalPrice: 160,
    discount: 40,
    rating: 4.5,
    reviews: 88,
    image: "/iphone16.png",
  },
  {
    id: 10,
    name: "HAVIT HV-G92 Gamepad",
    price: 120,
    originalPrice: 160,
    discount: 40,
    rating: 5,
    reviews: 88,
    image: "/iphone16.png",
  },
];

// export const products: Products[] = [
//   {
//     productName: "Product 1",
//     productPrice: 120,
//     description: "This is a product description",
//     colors: ["red", "blue", "green"],
//     sizes: ["small", "medium", "large"],
//     images: [
//       "../../public/iphone16.png",
//       "../../public/iphone16.png",
//       "../../public/iphone16.png",
//     ],
//     rating: 4.5,
//     reviews: 100,
//   },
//   {
//     productName: "Product 2",
//     productPrice: 150,
//     description: "This is a product description",
//     colors: ["red", "blue", "green"],
//     sizes: ["small", "medium", "large"],
//     images: [
//       "../../public/iphone16.png",
//       "../../public/iphone16.png",
//       "../../public/iphone16.png",
//     ],
//     rating: 4.5,
//     reviews: 100,
//   },
//   {
//     productName: "Product 3",
//     productPrice: 200,
//     description: "This is a product description",
//     colors: ["red", "blue", "green"],
//     sizes: ["small", "medium", "large"],
//     images: [
//       "../../public/iphone16.png",
//       "../../public/iphone16.png",
//       "../../public/iphone16.png",
//     ],
//     rating: 4.5,
//     reviews: 100,
//   },
//   {
//     productName: "Product 4",
//     productPrice: 250,
//     description: "This is a product description",
//     colors: ["red", "blue", "green"],
//     sizes: ["small", "medium", "large"],
//     images: [
//       "../../public/iphone16.png",
//       "../../public/iphone16.png",
//       "../../public/iphone16.png",
//     ],
//     rating: 4.5,
//     reviews: 100,
//   },
//   {
//     productName: "Product 5",
//     productPrice: 300,
//     description: "This is a product description",
//     colors: ["red", "blue", "green"],
//     sizes: ["small", "medium", "large"],
//     images: [
//       "../../public/iphone16.png",
//       "../../public/iphone16.png",
//       "../../public/iphone16.png",
//     ],
//     rating: 4.5,
//     reviews: 100,
//   },
//   {
//     productName: "Product 6",
//     productPrice: 350,
//     description: "This is a product description",
//     colors: ["red", "blue", "green"],
//     sizes: ["small", "medium", "large"],
//     images: [
//       "https://via.placeholder.com/150",
//       "https://via.placeholder.com/150",
//       "https://via.placeholder.com/150",
//     ],
//     rating: 4.5,
//     reviews: 100,
//   },
//   {
//     productName: "Product 7",
//     productPrice: 400,
//     description: "This is a product description",
//     colors: ["red", "blue", "green"],
//     sizes: ["small", "medium", "large"],
//     images: [
//       "https://via.placeholder.com/150",
//       "https://via.placeholder.com/150",
//       "https://via.placeholder.com/150",
//     ],
//     rating: 4.5,
//     reviews: 100,
//   },
//   {
//     productName: "Product 8",
//     productPrice: 450,
//     description: "This is a product description",
//     colors: ["red", "blue", "green"],
//     sizes: ["small", "medium", "large"],
//     images: [
//       "https://via.placeholder.com/150",
//       "https://via.placeholder.com/150",
//       "https://via.placeholder.com/150",
//     ],
//     rating: 4.5,
//     reviews: 100,
//   },
//   {
//     productName: "Product 9",
//     productPrice: 500,
//     description: "This is a product description",
//     colors: ["red", "blue", "green"],
//     sizes: ["small", "medium", "large"],
//     images: [
//       "https://via.placeholder.com/150",
//       "https://via.placeholder.com/150",
//       "https://via.placeholder.com/150",
//     ],
//     rating: 4.5,
//     reviews: 100,
//   },
//   {
//     productName: "Product 10",
//     productPrice: 550,
//     description: "This is a product description",
//     colors: ["red", "blue", "green"],
//     sizes: ["small", "medium", "large"],
//     images: [
//       "https://via.placeholder.com/150",
//       "https://via.placeholder.com/150",
//       "https://via.placeholder.com/150",
//     ],
//     rating: 4.5,
//     reviews: 100,
//   },
//   {
//     productName: "Product 11",
//     productPrice: 600,
//     description: "This is a product description",
//     colors: ["red", "blue", "green"],
//     sizes: ["small", "medium", "large"],
//     images: [
//       "https://via.placeholder.com/150",
//       "https://via.placeholder.com/150",
//       "https://via.placeholder.com/150",
//     ],
//     rating: 4.5,
//     reviews: 100,
//   },
//   {
//     productName: "Product 12",
//     productPrice: 650,
//     description: "This is a product description",
//     colors: ["red", "blue", "green"],
//     sizes: ["small", "medium", "large"],
//     images: [
//       "https://via.placeholder.com/150",
//       "https://via.placeholder.com/150",
//       "https://via.placeholder.com/150",
//     ],
//     rating: 4.5,
//     reviews: 100,
//   },
//   {
//     productName: "Product 13",
//     productPrice: 700,
//     description: "This is a product description",
//     colors: ["red", "blue", "green"],
//     sizes: ["small", "medium", "large"],
//     images: [
//       "https://via.placeholder.com/150",
//       "https://via.placeholder.com/150",
//       "https://via.placeholder.com/150",
//     ],
//     rating: 4.5,
//     reviews: 100,
//   },
//   {
//     productName: "Product 14",
//     productPrice: 750,
//     description: "This is a product description",
//     colors: ["red", "blue", "green"],
//     sizes: ["small", "medium", "large"],
//     images: [
//       "https://via.placeholder.com/150",
//       "https://via.placeholder.com/150",
//       "https://via.placeholder.com/150",
//     ],
//     rating: 4.5,
//     reviews: 100,
//   },
//   {
//     productName: "Product 15",
//     productPrice: 800,
//     description: "This is a product description",
//     colors: ["red", "blue", "green"],
//     sizes: ["small", "medium", "large"],
//     images: [
//       "https://via.placeholder.com/150",
//       "https://via.placeholder.com/150",
//       "https://via.placeholder.com/150",
//     ],
//     rating: 4.5,
//     reviews: 100,
//   },
//   {
//     productName: "Product 16",
//     productPrice: 850,
//     description: "This is a product description",
//     colors: ["red", "blue", "green"],
//     sizes: ["small", "medium", "large"],
//     images: [
//       "https://via.placeholder.com/150",
//       "https://via.placeholder.com/150",
//       "https://via.placeholder.com/150",
//     ],
//     rating: 4.5,
//     reviews: 100,
//   },
//   {
//     productName: "Product 17",
//     productPrice: 900,
//     description: "This is a product description",
//     colors: ["red", "blue", "green"],
//     sizes: ["small", "medium", "large"],
//     images: [
//       "https://via.placeholder.com/150",
//       "https://via.placeholder.com/150",
//       "https://via.placeholder.com/150",
//     ],
//     rating: 4.5,
//     reviews: 100,
//   },
//   {
//     productName: "Product 18",
//     productPrice: 950,
//     description: "This is a product description",
//     colors: ["red", "blue", "green"],
//     sizes: ["small", "medium", "large"],
//     images: [
//       "https://via.placeholder.com/150",
//       "https://via.placeholder.com/150",
//       "https://via.placeholder.com/150",
//     ],
//     rating: 4.5,
//     reviews: 100,
//   },
//   {
//     productName: "Product 19",
//     productPrice: 1000,
//     description: "This is a product description",
//     colors: ["red", "blue", "green"],
//     sizes: ["small", "medium", "large"],
//     images: [
//       "https://via.placeholder.com/150",
//       "https://via.placeholder.com/150",
//       "https://via.placeholder.com/150",
//     ],
//     rating: 4.5,
//     reviews: 100,
//   },
//   {
//     productName: "Product 20",
//     productPrice: 1050,
//     description: "This is a product description",
//     colors: ["red", "blue", "green"],
//     sizes: ["small", "medium", "large"],
//     images: [
//       "https://via.placeholder.com/150",
//       "https://via.placeholder.com/150",
//       "https://via.placeholder.com/150",
//     ],
//     rating: 4.5,
//     reviews: 100,
//   },
//   {
//     productName: "Product 21",
//     productPrice: 1100,
//     description: "This is a product description",
//     colors: ["red", "blue", "green"],
//     sizes: ["small", "medium", "large"],
//     images: [
//       "https://via.placeholder.com/150",
//       "https://via.placeholder.com/150",
//       "https://via.placeholder.com/150",
//     ],
//     rating: 4.5,
//     reviews: 100,
//   },
//   {
//     productName: "Product 22",
//     productPrice: 1150,
//     description: "This is a product description",
//     colors: ["red", "blue", "green"],
//     sizes: ["small", "medium", "large"],
//     images: [
//       "https://via.placeholder.com/150",
//       "https://via.placeholder.com/150",
//       "https://via.placeholder.com/150",
//     ],
//     rating: 4.5,
//     reviews: 100,
//   },
//   {
//     productName: "Product 23",
//     productPrice: 1200,
//     description: "This is a product description",
//     colors: ["red", "blue", "green"],
//     sizes: ["small", "medium", "large"],
//     images: [
//       "https://via.placeholder.com/150",
//       "https://via.placeholder.com/150",
//       "https://via.placeholder.com/150",
//     ],
//     rating: 4.5,
//     reviews: 100,
//   },
//   {
//     productName: "Product 24",
//     productPrice: 1250,
//     description: "This is a product description",
//     colors: ["red", "blue", "green"],
//     sizes: ["small", "medium", "large"],
//     images: [
//       "https://via.placeholder.com/150",
//       "https://via.placeholder.com/150",
//       "https://via.placeholder.com/150",
//     ],
//     rating: 4.5,
//     reviews: 100,
//   },
//   {
//     productName: "Product 25",
//     productPrice: 1300,
//     description: "This is a product description",
//     colors: ["red", "blue", "green"],
//     sizes: ["small", "medium", "large"],
//     images: [
//       "https://via.placeholder.com/150",
//       "https://via.placeholder.com/150",
//       "https://via.placeholder.com/150",
//     ],
//     rating: 4.5,
//     reviews: 100,
//   },
//   {
//     productName: "Product 26",
//     productPrice: 1350,
//     description: "This is a product description",
//     colors: ["red", "blue", "green"],
//     sizes: ["small", "medium", "large"],
//     images: [
//       "https://via.placeholder.com/150",
//       "https://via.placeholder.com/150",
//       "https://via.placeholder.com/150",
//     ],
//     rating: 4.5,
//     reviews: 100,
//   },
//   {
//     productName: "Product 27",
//     productPrice: 1400,
//     description: "This is a product description",
//     colors: ["red", "blue", "green"],
//     sizes: ["small", "medium", "large"],
//     images: [
//       "https://via.placeholder.com/150",
//       "https://via.placeholder.com/150",
//       "https://via.placeholder.com/150",
//     ],
//     rating: 4.5,
//     reviews: 100,
//   },
// ];

export const categories = [
  {
    id: 1,
    name: "Summer",
    imageUrl: Smartphone,
  },
  {
    id: 2,
    name: "Limited",
    imageUrl: Smartphone,
  },
  {
    id: 3,
    name: "New",
    imageUrl: Smartphone,
  },
  {
    id: 4,
    name: "Essentials",
    imageUrl: Smartphone,
  },
  {
    id: 5,
    name: "Accessories",
    imageUrl: Smartphone,
  },
  {
    id: 6,
    name: "Collections",
    imageUrl: Smartphone,
  },
  {
    id: 7,
    name: "Sale",
    imageUrl: Smartphone,
  },
  {
    id: 8,
    name: "Gifts",
    imageUrl: Smartphone,
  },
];

export const slides: Slides[] = [
  {
    id: 1,
    imageUrl: "/iphonebanner.jpg",
    title: "",
    description: "",
    link: "/collections/summer",
  },
  {
    id: 2,
    imageUrl: "/applewatchbanner.jpg",
    title: "",
    description: "",
    link: "/collections/limited",
  },
  {
    id: 3,
    imageUrl: "/playstationbanner.jpg",
    title: "",
    description: "",
    link: "/collections/new",
  },
  {
    id: 4,
    imageUrl: "/xboxbanner.jpg",
    title: "",
    description: "",
    link: "/collections/essentials",
  },
];
